In [8]:
import numpy as np


In [17]:
x = [0, 0, 1, 0,0,0,0,0,0,0]
y = [0, 1, 0, 2,1, 0, 0, 1,1,1]

print(np.correlate(x,y, 'full'))


[0 0 1 1 1 0 0 1 2 0 1 0 0 0 0 0 0 0 0]


In [31]:
print(np.convolve(x,y))

[0 0 0 1 0 2 1 0 0 1 1 1 0 0 0 0 0 0 0]


In [28]:
X = np.fft.fft(x)
Y = np.fft.fft(y)

print(X*Y)
print(np.roll(np.around(abs(np.fft.ifft(X*Y)), 2),-2))

[ 7.00000000 +0.00000000e+00j -0.50000000 -3.63271264e-01j
  3.11803399 -3.63271264e-01j -0.50000000 +1.53884177e+00j
  0.88196601 -1.53884177e+00j -3.00000000 +1.83186799e-15j
  0.88196601 +1.53884177e+00j -0.50000000 -1.53884177e+00j
  3.11803399 +3.63271264e-01j -0.50000000 +3.63271264e-01j]
[ 0.  1.  0.  2.  1.  0.  0.  1.  1.  1.]
